id: I758D1AB7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T09:26:45+00:00'
last_modified: '2022-06-08T06:36:27.918208+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ2284
  title: རོལ་མོའི་འཇུག་སྒོ་སྒྲ་དབྱངས་བློ་མདུད་ཀུན་གྲོལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    EEA6:
      image_group_id: I1CZ2318
      title: ''
      total_pages: 90
      order: 1
      base_file: EEA6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
