id: P006752
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ2284
  title: རོལ་མོའི་འཇུག་སྒོ་སྒྲ་དབྱངས་བློ་མདུད་ཀུན་གྲོལ
  author: ''
  volumes:
    67c4268522cd48619984127254d488fc:
      image_group_id: I1CZ2318
      title: ''
      volume_number: 1
      total_pages: 90
      base_file: v001.txt
